[server]
host='localhost'
port=8080

[http]
allowed_origins='http://localhost:8080'
allowed_methods='*'
rate_limit=2
rate_limit_window=1
worker_pool_size=4

[logger]
level='DEBUG'
log_file='logs/app.log'
error_log_file='logs/error.log'
disabled=false

[env]
local=true

[mock]
remote_addr="151.101.193.69:443"